name = "oeis_a112521_fc"
version = "0.1.0"
defaultTargets = ["OeisA112521FC"]

[[require]]
name = "formal_conjectures"
git = "https://github.com/google-deepmind/formal-conjectures"
rev = "230782e37bbf5aa0cab03874e876626beacac009"

[[lean_lib]]
name = "OeisA112521FC"

[[lean_lib]]
name = "OeisA112521Proof"
